name: Update AQHI (GeoMet)

permissions:
  contents: write   
  
on:
  schedule: [ { cron: "7 * * * *" } ]
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: pip install requests pandas folium
      - run: |
          python scripts/aqhi_geomet_to_geojson.py \
            --out-csv data/aqhi_points.csv \
            --out-geojson data/aqhi_points.geojson \
            --out-html data/aqhi_map.html
      - run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add data/
          git commit -m "Update AQHI data" || echo "No changes"
          git push
